# Generated by Django 3.0 on 2020-03-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttributeName', models.CharField(max_length=80, null=True, unique=True)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttributeValues', models.CharField(max_length=120)),
                ('logo', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('Attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.Attributes')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=80, unique=True)),
                ('logo', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerClass', models.CharField(max_length=80, unique=True)),
                ('logo', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=80, unique=True)),
                ('logo', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(default='Y', max_length=1)),
                ('Attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.Attributes')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductNature', models.CharField(max_length=80, unique=True)),
                ('logo', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeasonName', models.CharField(max_length=80, unique=True)),
                ('CalendarYear', models.IntegerField()),
                ('CalendarDate', models.DateTimeField()),
                ('description', models.CharField(max_length=400)),
                ('active', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=80, unique=True)),
                ('logo', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.categories')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=800)),
                ('ProductImage', models.TextField(max_length=255)),
                ('ProductPrice', models.IntegerField()),
                ('SalePrice', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('caption', models.CharField(max_length=80)),
                ('tag', models.CharField(max_length=1)),
                ('active', models.CharField(default='Y', max_length=1)),
                ('CreateDBy', models.CharField(max_length=80)),
                ('ModifiedBy', models.CharField(max_length=80)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now_add=True)),
                ('ProductCode', models.TextField(max_length=120)),
                ('CustomerClasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.CustomerClasses')),
                ('ProductNatures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.ProductNatures')),
                ('Seasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.Seasons')),
                ('SubCategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.SubCategories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefProductId', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SmallImage', models.TextField(max_length=255)),
                ('LargeImage', models.TextField(max_length=255)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(default='N', max_length=1)),
                ('AttributeValues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.AttributeValues')),
                ('ProductAttributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.ProductAttributes')),
            ],
        ),
        migrations.AddField(
            model_name='productattributes',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.products'),
        ),
        migrations.AddField(
            model_name='categories',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fadollproducts.departments'),
        ),
    ]
